version: '3.8'

services:
  api-gateway:
    build: .
    container_name: api-gateway
    ports:
      - "4004:4004"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:4005
    networks:
      - shared-network

networks:
  shared-network:
    external: true